apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-anubhav-docker
  labels:
    app: hello-anubhav-docker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-anubhav-docker
  template:
    metadata:
      labels:
        app: hello-anubhav-docker
    spec:
      containers:
        - image: gcr.io/disco-plane-327514/hello-anubhav-docker
          name: hello-anubhav-docker-container
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              port: 8080
              path: /api/status
            initialDelaySeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              port: 8080
              path: /api/status
            initialDelaySeconds: 5
            failureThreshold: 5